---
model: 'BD_TransformerModel'
dst_vocab: '/data/nfs_rt22/TTS/chenxi/projects/bd-asr/data/bd_vocab'
apply_sentence_cmvn: False # Use global cmvn
global_cmvn_file: '/data/nfs_rt22/TTS/chenxi/projects/bd-asr/data/global_cmvn.txt'
dst_vocab_size: 4336
hidden_units: 512
scale_embedding: True
tie_embedding_and_softmax: True
attention_dropout_rate: 0.0
residual_dropout_rate: 0.2
encoder_num_blocks: 8
decoder_num_blocks: 4
ff_units: 4
num_heads: 8
ff_activation: 'glu'
model_dir: '/data/nfs_rt22/TTS/chenxi/projects/bd-asr/save/bd_8_4_4gpus_512units_spec'
spec_aug: True # use spec aug
train:
    num_gpus: 4
    feat_file_pattern: '/data/nfs_rt22/TTS/chenxi/projects/kaldi/egs/aishell/s5/fbank/raw_fbank_train.*.scp'
    label_file: '/data/nfs_rt22/TTS/chenxi/projects/bd-asr/data/text'
    sudo_l2r_target: '/data/nfs_rt22/TTS/chenxi/projects/bd-asr/data/text'
    sudo_r2l_target: '/data/nfs_rt22/TTS/chenxi/projects/bd-asr/data/text'
    frame_bucket_limit: '[200, 300, 500, 800, 1200, 1400, 1800, 3000]'
    batch_bucket_limit_per_gpu: '[220, 200, 180, 140, 100, 100, 60, 20]'
    batch_factor: 0.3
    debug: False
    target_len_limit: 100
    num_epochs: 70
    max_steps: 240000
    save_freq: -500
    summary_freq: 100
    eval_on_dev: True
    grads_clip: 5
    optimizer: 'adam_decay'
    learning_rate: 1
    warmup_steps: 16000
    label_smoothing: 0.1
    input_dim: 240
    var_filter: ''
dev:
    feat_file_pattern: '/data/nfs_rt22/TTS/chenxi/projects/kaldi/egs/aishell/s5/fbank/raw_fbank_dev.[1-4].ark'
    output_file: '/data/nfs_rt22/TTS/chenxi/projects/bd-asr/save/bd_8_4_4gpus_512units_spec/dev_decoding_results/'

test:
    batch_size: 40
    max_target_length: 200
    lp_alpha: 0.6
    beam_size: 2
    num_gpus: 2
    checkpoint: 'model_epoch_50'
    set1:
        feat_file_pattern: '/data/nfs_rt22/TTS/chenxi/projects/kaldi/egs/aishell/s5/fbank/raw_fbank_test.[1-4].ark'
        label_file: ''
        output_path: '/data/nfs_rt22/TTS/chenxi/projects/bd-asr/save/bd_8_4_4gpus_512units_spec/test_decoding_results/bd_decoder_8_4_4gpus_epoch_50.txt'
        cmd:
