---
model: 'BD_TransformerModel'
dst_vocab: '/datadisk/datasets/aishell2/train/train_units_bd.txt'
apply_sentence_cmvn: False # Use global cmvn
global_cmvn_file: '/datadisk/datasets/aishell2/train/global_cmvn.txt'
dst_vocab_size: 5210
#### hidden_units: 512
hidden_units: 512
scale_embedding: True
tie_embedding_and_softmax: True
attention_dropout_rate: 0.0
residual_dropout_rate: 0.2
encoder_num_blocks: 8
decoder_num_blocks: 4
ff_units: 4
latent_k_dim: 50
latent_v_dim: 50
#### num_heads: 8
num_heads: 8
mask_prob: 0.0
mask_rate: 0.0
ff_activation: 'glu'
#model_dir: '/data00/home/labspeech_intern/chenxi/project/rebuild_transformerasr/bd_transformer_aishell_model'
model_dir: '/datadisk/model/aishell2/bd/bd_transformer_8_4_4gpus_512units_exp1'
# Discarded
#bucket_min: 50
# Discarded
#bucket_max: 10000
# Discarded
#bucket_step: 10
#min_count_in_bucket: 100
train:
    num_gpus: 4
    #tokens_per_batch: 50000
    feat_file_pattern: '/datadisk/datasets/aishell2/train/feature/feats.*.scp'
    label_file: '/datadisk/datasets/aishell2/train/text'
    sudo_l2r_target: '/datadisk/datasets/aishell2/train/text'
    sudo_r2l_target: '/datadisk/datasets/aishell2/train/text'
    frame_bucket_limit: '[200, 300, 500, 800, 1200, 1400, 1800, 3000]'
    batch_bucket_limit_per_gpu: '[220, 200, 180, 140, 100, 100, 60, 20]'
    batch_factor: 0.3
    debug: False
    target_len_limit: 100
    #max_length: 5000
    num_epochs: 50
    # Discarded
    #num_steps: 300000
    max_steps: 240000
    # debug: 200, train: 500
    save_freq: -500
    # show_freq: 10
    summary_freq: 100
    eval_on_dev: True
    grads_clip: 5
    optimizer: 'adam_decay'
    learning_rate: 1
    warmup_steps: 16000
    label_smoothing: 0.1
    #toleration: 10
#    input_dim: 129
#    input_dim: 516
    input_dim: 240
    var_filter: ''
dev:
    feat_file_pattern: '/datadisk/datasets/aishell2/dev/ark/raw_fbank_dev.[1-4].ark'
    output_file: '/datadisk/decoder_result/aishell2/bd/bd_8_4_4gpus_512units_exp1/'

test:
    batch_size: 40
    max_target_length: 200
    lp_alpha: 0.6
    beam_size: 2
    num_gpus: 4
    checkpoint: 'model_step_200000'
    set1:
        feat_file_pattern: '/datadisk/datasets/aishell2/test/ark/raw_fbank_test.[1-4].ark'
        label_file: ''
        output_path: '/datadisk/decoder_result/aishell2/bd_decoder_8_4_4gpus_512units_exp1_200k.txt'
        cmd: